name: address_search_field_example
description: Demonstrates how to use the address_search_field plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  address_search_field:
    path: ../

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.1
  location: ^4.1.1

dev_dependencies:
  build_runner: ^1.11.5
  build_web_compilers: ^2.16.4

flutter:
  uses-material-design: true
