name: address_search_text_field
description: An address search box that gets nearby addresses by typing a reference, returns an object with place primary data. The object can also find an address using coordinates.
version: 1.2.2
author: José Luna <josluna1098@gmail.com>
homepage: https://github.com/JosLuna98/address_search_text_field.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^5.3.0
  geocoder: ^0.2.1
  location: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
