name: address_search_field
description: An address search field which helps to autocomplete an address by a reference. It can be used to get Directions beetwen two points.
version: 2.0.0+1
homepage: https://github.com/JosLuna98/address_search_field.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  google_maps_flutter: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
